name: Bug Report
description: Create a report to help us improve
title: "Bug: "
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our mod!
        Make sure to leave a helpful title.
        If your issue crashed your game, instead issue a [crash report](https://github.com/devs-immortal/Paradise-Lost/issues/new?assignees=&labels=Bug&template=crash-report.yml&title=Crash%3A+).
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen and how to replicate it
      value: |
        A bug!

        To replicate:
        1. First, I ...
        1. Next, ...
        1. Finally, ...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Mod Version
      description: What version of our mod are you running?
      options:
        # Figure out how to make this automatic.
        - "1.6.5 - 1.18"
        - "1.6.5 - 1.17"
        - "1.6.3"
        - "1.6.x"
        - "Older"
        - "Unsure"
        - "Dev"
    validations:
      required: true
  - type: input
    id: fapi-version
    attributes:
      label: Fabric API Version
      description: What version of Fabric API are you using?
      placeholder: ex. 0.xx.x
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste the logs from the event of the bug. The latest log can be found in `.minecraft/logs/latest.log.`
      render: shell
    validations:
      required: false
  - type: textarea
    id: mods
    attributes:
      label: Other mods
      description: If you're using other mods, please share a zip of your mods folder here. If you're not, you can leave this blank.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Additional Information
      description: Is there anything else we should know?
      placeholder: ex. I'm using a third party launcher
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Have any relevant screenshots? Share them!
