name: Crash Report
description: Report a crash
title: "Crash: "
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our mod!
        Make sure to leave a helpful title.
  - type: textarea
    id: what-happened
    attributes:
      label: What were you doing when the crash occured?
      value: |
        1. First, ...
        1. Next, ...
        1. Finally, ...
    validations:
      required: true
  - type: dropdown
    id: client-server
    attributes:
      label: Did it crash the client or server?
      description: If you don't know what this means, pick "Unsure".
      options:
        - Client
        - Server
        - Both
        - Unsure
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Mod Version
      description: What version of our mod were you running?
      options:
        # Figure out how to make this automatic.
        - "1.6.5 - 1.18"
        - "1.6.5 - 1.17"
        - "1.6.3"
        - "1.6.x"
        - "Other"
        - "Unsure"
        - "Dev"
    validations:
      required: true
  - type: input
    id: fapi-version
    attributes:
      label: Fabric API Version
      description: What version of Fabric API were you using?
      placeholder: ex. 0.xx.x
    validations:
      required: false
  - type: textarea
    id: crash-report
    attributes:
      label: Crash Report
      description: |
        Please copy and paste the crash report here. If there was none provided, the latest log can be found in `.minecraft/logs/latest.log.`
      render: shell
    validations:
      required: true
  - type: textarea
    id: mods
    attributes:
      label: Other mods
      description: If you're using other mods, please share a zip of your mods folder here. If you're not, you can leave this blank.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Additional Information
      description: Is there anything else we should know?
      placeholder: ex. I'm using a third party launcher
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Have any relevant screenshots? Share them!
